from flask import Flask, request, jsonify
import requests

app = Flask(__name__)

COUNTRY_TO_LOCALE = {
    "ID": "id",
    "US": "en-us",
    "GB": "en-gb",
    "MY": "ms-my",
    "JP": "ja",
    "KR": "ko",
    "CN": "zh-cn",
    "TW": "zh-tw",
    "SG": "zh-sg",
    "TH": "th",
    "VN": "vi",
    "PH": "tl",
    "RU": "ru",
    "DE": "de-de",
    "FR": "fr-fr",
    "IT": "it",
    "ES": "es-es",
    "PT": "pt-pt",
    "BR": "pt-br",
    "AR": "es-ar",
    "MX": "es-mx",
    "SA": "ar",
    "TR": "tr",
    "IN": "hi",
    "PK": "ur",
    "BD": "bn",
    "UA": "uk",
    "PL": "pl",
    "NL": "nl",
    "SE": "sv",
    "NO": "nb",
    "FI": "fi",
    "DK": "da",
    "AU": "en-au",
    "CA": "en-ca",
    "NZ": "en-nz",
    "AF": "fa",
    "AL": "sq",
    "DZ": "ar-dz",
    "AD": "ca",
    "AO": "pt-ao",
    "AG": "en-ag",
    "AM": "hy",
    "AT": "de-at",
    "AZ": "az",
    "BS": "en-bs",
    "BH": "ar-bh",
    "BB": "en-bb",
    "BY": "be",
    "BZ": "en-bz",
    "BJ": "fr-bj",
    "BT": "dz",
    "BO": "es-bo",
    "BA": "bs",
    "BW": "tn",
    "BN": "ms-bn",
    "BG": "bg",
    "BF": "fr-bf",
    "BI": "rn",
    "CV": "pt-cv",
    "KH": "km",
    "CM": "fr-cm",
    "CF": "fr-cf",
    "TD": "fr-td",
    "CL": "es-cl",
    "CO": "es-co",
    "KM": "ar-km",
    "CR": "es-cr",
    "HR": "hr",
    "CU": "es-cu",
    "CY": "el-cy",
    "CZ": "cs",
    "CD": "fr-cd",
    "DJ": "fr-dj",
    "DM": "en-dm",
    "DO": "es-do",
    "EC": "es-ec",
    "EG": "ar-eg",
    "SV": "es-sv",
    "GQ": "fr-gq",
    "ER": "ti-er",
    "EE": "et",
    "SZ": "en-sz",
    "ET": "am",
    "FJ": "en-fj",
    "FI": "fi",
    "GA": "fr-ga",
    "GM": "en-gm",
    "GE": "ka",
    "GH": "ak",
    "GR": "el",
    "GD": "en-gd",
    "GT": "es-gt",
    "GN": "fr-gn",
    "GW": "pt-gw",
    "GY": "en-gy",
    "HT": "fr-ht",
    "HN": "es-hn",
    "HU": "hu",
    "IS": "is",
    "IR": "fa-ir",
    "IQ": "ar-iq",
    "IE": "en-ie",
    "IL": "he",
    "CI": "fr-ci",
    "JM": "en-jm",
    "JO": "ar-jo",
    "KZ": "kk",
    "KE": "sw-ke",
    "KI": "en-ki",
    "KW": "ar-kw",
    "KG": "ky",
    "LA": "lo",
    "LV": "lv",
    "LB": "ar-lb",
    "LS": "st-ls",
    "LR": "en-lr",
    "LY": "ar-ly",
    "LT": "lt",
    "MG": "mg",
    "MC": "fr-mc",
    "MA": "ar-ma",
    "MM": "my",
    "NP": "ne",
    "NI": "nb",
    "OM": "ar-om",
    "PS": "ar-ps",
    "QA": "ar-qa",
    "RO": "ro",
    "RW": "rn",
    "KN": "en-ag",
    "LC": "en-ag",
    "VC": "en-ag",
    "WS": "en-ag",
    "SM": "it",
    "ST": "pt-cv",
    "SN": "fr-ga",
    "RS": "bs",
    "SC": "fr-ga",
    "SL": "en-lr",
    "SK": "cs",
    "SI": "bs",
    "SB": "en-ki",
    "SO": "ar-eg",
    "ZA": "en-gb",
    "SS": "en-gb",
    "LK": "hi",
    "SD": "ar-eg",
    "SR": "en-gy",
    "SE": "sv",
    "CH": "de-de",
    "SY": "ar-eg",
    "TJ": "kk",
    "TZ": "sw-ke",
    "TL": "tl",
    "TG": "fr-bj",
    "TO": "en-ki",
    "TT": "en-ag",
    "TN": "ar-eg",
    "TM": "kk",
    "TV": "en-ki",
    "UG": "sw-ke",
    "AE": "ar-ae",
    "UY": "es-ar",
    "UZ": "kk",
    "VU": "en-ki",
    "VE": "es-ar",
    "YE": "ar-eg",
    "ZM": "en-gb",
    "ZW": "en-gb",
}

@app.route('/getflag', methods=['GET'])
def get_flag():
    # Coba dapat dari IP dulu
    ip = request.args.get('ip', '')
    # Kalau tidak ada IP, pakai locale langsung
    locale_param = request.args.get('locale', '')

    if locale_param:
        return jsonify({
            "locale": locale_param,
            "country": "unknown",
            "code": "unknown"
        })

    if not ip:
        return jsonify({"locale": "default", "country": "unknown"})

    try:
        res = requests.get(f"http://ip-api.com/json/{ip}?fields=countryCode,country", timeout=3)
        data = res.json()
        country_code = data.get("countryCode", "").upper()
        locale = COUNTRY_TO_LOCALE.get(country_code, "default")
        return jsonify({
            "locale": locale,
            "country": data.get("country", "unknown"),
            "code": country_code
        })
    except:
        return jsonify({"locale": "default", "country": "unknown"})

@app.route('/', methods=['GET'])
def index():
    return jsonify({"status": "Flag Backend Running!"})

if __name__ == '__main__':
    import os
    port = int(os.environ.get('PORT', 8080))
    app.run(host='0.0.0.0', port=port)
